source 'https://rubygems.org'
ruby '2.1.1'
gem 'rails', '4.0.3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass', '>= 3.0.0.0'
gem 'pg'
gem 'thin'
gem 'bcrypt-ruby'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'faker'
gem 'simple_form'
gem 'placeholdit'
gem 'paperclip'
gem 'aws-sdk'
gem 'challonge-api'
gem 'paypal-sdk-rest'
group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'hub', :require=>nil
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'rails_12factor'
end
group :development, :test do
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'spork-rails'
  gem 'guard-spork'
  gem 'childprocess'
  gem 'pry-debugger'
end
group :test do
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'database_cleaner', '1.0.1'
  gem 'email_spec'
  gem 'growl'
end
